<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Doctrine</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
<div class="container">
    <div class="row">
        <h3>Adicionar categorias</h3>
        <h5><?php echo "Post = {$post->getTitle()}"?></h5>
        <form action="/posts/<?=$post->getId()?>/set-categories" name="form" method="post">

            <div class="form-group">
                <label for="categories">Categories</label>
                <select name="categories[]" id="" class="form-control" multiple>
                    <?php foreach ($categories as $category):?>
                        <option value="<?=$category->getId()?>" <?php echo $post->getCategories()->contains($category) ? 'selected="selected"' : "" ?>>
                            <?=$category->getName()?>
                        </option>
                    <?php endforeach;?>
                </select>
            </div>

            <button class="btn btn-default" type="submit">Enviar</button>
        </form>
    </div>
</div>
</body>
</html>