<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Doctrine</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
    <div class="container">
        <div class="row">
            <h3>Listagem de Posts</h3>
            <a href="/posts/create" class="btn btn-default">Novo Post</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Ação</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($posts as $post):?>
                    <tr>
                        <td><?=$post->getId()?></td>
                        <td><?=$post->getTitle()?></td>
                        <td>
                            <a href="/posts/<?=$post->getId()?>/categories">Categories</a>|
                            <a href="/posts/<?=$post->getId()?>/edit">Editar</a>|
                            <a href="/posts/<?=$post->getId()?>/remove">Excluir</a>
                        </td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>
