<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Doctrine</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
<div class="container">
    <div class="row">
        <h3>POSTS</h3>
        <div class="col-md-10">
            <ul class="list-unstyled">
                <li>
                    <?php foreach ($posts as $post): ?>
                        <div class="jumbotron">
                            <h1><?=$post->getTitle()?></h1>
                            <p><?=substr($post->getContent(),0,20)?>...</p>
                            <p><a href="#" class="btn btn-primary btn-lg">Leia mais</a></p>
                        </div>
                    <?php endforeach;?>
                </li>
            </ul>
        </div>
        <div class="col-md-2">
            <ul class="list-group">
                <?php foreach ($categories as $category): ?>
                    <li class="list-group-item">
                        <a href="/?search=<?=$category->getId()?>"><?=$category->getName()?></a>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>

    </div>
</div>
</body>
</html>
